<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Exporting a dataframe into a LaTeX table

## Importing the required libraries

In [1]:
import pandas as pd

## Loading the data into a dataframe

In [2]:
df = pd.read_excel('Table.xlsx')

In [3]:
df

,Category,Indicators,Definition,Occurrences,%
0,Affective response,NaN,NaN,62.0,0.455882
1,NaN,Expression of emotions,Conspicuous capitalisation,3.0,0.022059
2,NaN,NaN,Emoji (*),10.0,0.073529
3,NaN,NaN,Emoticon,9.0,0.066176
4,NaN,NaN,Empathy (*),2.0,0.014706
5,NaN,NaN,Exclamation (*),14.0,0.102941
6,NaN,NaN,Expressing surprise (*),1.0,0.007353
7,NaN,NaN,Expression of emotion,8.0,0.058824
8,NaN,Self-disclosure,NaN,7.0,0.051471
9,NaN,Use of humour,NaN,8.0,0.058824
10,Interactive response,NaN,NaN,47.0,0.345588
11,NaN,Asking questions,NaN,1.0,0.007353
12,NaN,Disclosing the lie (*),NaN,1.0,0.007353
13,NaN,Expressing agreement,NaN,1.0,0.007353
14,NaN,Expressing appreciation,NaN,20.0,0.147059
15,NaN,Referring to other's messages,NaN,1.0,0.007353
16,NaN,Trying to spot the lie (*),NaN,23.0,0.169118
17,Cohesive response,NaN,NaN,27.0,0.198529
18,NaN,Addressing the group,NaN,4.0,0.029412
19,NaN,Salutation,NaN,23.0,0.169118
20,NaN,NaN,NaN,136.0,1.000000
21,NaN,NaN,NaN,NaN,NaN
22,(*) defined by me,NaN,NaN,NaN,NaN

### Converting the column `%` into percentages

In [4]:
df['%'] = df['%']*100

In [5]:
df

,Category,Indicators,Definition,Occurrences,%
0,Affective response,NaN,NaN,62.0,45.588235
1,NaN,Expression of emotions,Conspicuous capitalisation,3.0,2.205882
2,NaN,NaN,Emoji (*),10.0,7.352941
3,NaN,NaN,Emoticon,9.0,6.617647
4,NaN,NaN,Empathy (*),2.0,1.470588
5,NaN,NaN,Exclamation (*),14.0,10.294118
6,NaN,NaN,Expressing surprise (*),1.0,0.735294
7,NaN,NaN,Expression of emotion,8.0,5.882353
8,NaN,Self-disclosure,NaN,7.0,5.147059
9,NaN,Use of humour,NaN,8.0,5.882353
10,Interactive response,NaN,NaN,47.0,34.558824
11,NaN,Asking questions,NaN,1.0,0.735294
12,NaN,Disclosing the lie (*),NaN,1.0,0.735294
13,NaN,Expressing agreement,NaN,1.0,0.735294
14,NaN,Expressing appreciation,NaN,20.0,14.705882
15,NaN,Referring to other's messages,NaN,1.0,0.735294
16,NaN,Trying to spot the lie (*),NaN,23.0,16.911765
17,Cohesive response,NaN,NaN,27.0,19.852941
18,NaN,Addressing the group,NaN,4.0,2.941176
19,NaN,Salutation,NaN,23.0,16.911765
20,NaN,NaN,NaN,136.0,100.000000
21,NaN,NaN,NaN,NaN,NaN
22,(*) defined by me,NaN,NaN,NaN,NaN

## Exporting the dataframe into a LaTeX table

Please refer to [pandas.DataFrame.to_latex](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_latex.html#pandas.DataFrame.to_latex).

In [6]:
df_latex = df.to_latex(index=False, float_format='%.2f', longtable=True, decimal=',', caption='Social presence assessment', label='tab:social_presence_assessment')

## Saving the LaTeX table into a file

In [7]:
with open('Table.tex', 'w', encoding='utf8', newline='\n') as file:
    file.write(df_latex)